version: '3'
services:
  springapp:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vnpay_sandbox
    expose:
      - 8080
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vnpay_sandbox

